name: Pull latest seeded DB image
on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/db-push-latest-seeded-image.yaml
#  push:
#    branches:
#      - master
#    paths:
#      - .github/workflows/db-push-latest-seeded-image.yaml

  workflow_dispatch:

jobs:
  pull-user-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          SCHEMA_SHA=$(git hash-object ./js/mine.js)
          USER_DB_NEW=asia.gcr.io/beatrust-devs/user-db:$SCHEMA_SHA
          USER_DB_LATEST=asia.gcr.io/beatrust-devs/user-db:latest-seeded

          DIGEST_1=$(docker pull $USER_DB_NEW | grep "Digest:")
          DIGEST_2=$(docker pull $USER_DB_LATEST | grep "Digest:")
  
          if [ "$DIGEST_1" = "$DIGEST_2" ]; then
            exit 1
          else
            docker tag $USER_DB_NEW $USER_DB_LATEST
            docker push $USER_DB_LATEST
          fi
