name: Pull latest seeded DB image
on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/db-push-latest-seeded-image.yaml
#  push:
#    branches:
#      - master
#    paths:
#      - .github/workflows/db-push-latest-seeded-image.yaml

  workflow_dispatch:

jobs:
  pull-user-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          SCHEMA_SHA=$(git hash-object ./js/mine.js)
          echo $SCHEMA_SHA
          docker pull postgres:13
          docker pull postgres:25
          docker images --digests
